version: '3'

services:
  oidc-mock:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BASE_URL=http://localhost:8000
      - SERVER_NAME=oidc-mock
    volumes:
      - ./app:/app 